#pragma once
#include <array>

struct Dependency
{
    wchar_t Step;
    wchar_t Requirement;
};

// Convert input data with this regex:
// %s/Step \(\w\) must be finished before step \(\w\) can begin\./    { L'\2', L'\1' },
const std::array<Dependency, 7> sample_steps = { {
    { L'A', L'C' },
    { L'F', L'C' },
    { L'B', L'A' },
    { L'D', L'A' },
    { L'E', L'B' },
    { L'E', L'D' },
    { L'E', L'F' },
} };

const std::array<Dependency, 101> input_steps = { {
    { L'R', L'F' },
    { L'P', L'I' },
    { L'O', L'C' },
    { L'K', L'H' },
    { L'N', L'Y' },
    { L'J', L'M' },
    { L'W', L'D' },
    { L'N', L'B' },
    { L'A', L'T' },
    { L'L', L'R' },
    { L'S', L'P' },
    { L'J', L'O' },
    { L'N', L'X' },
    { L'K', L'A' },
    { L'G', L'N' },
    { L'U', L'W' },
    { L'U', L'Q' },
    { L'U', L'V' },
    { L'G', L'J' },
    { L'S', L'G' },
    { L'U', L'Z' },
    { L'S', L'U' },
    { L'L', L'E' },
    { L'L', L'K' },
    { L'S', L'L' },
    { L'N', L'M' },
    { L'E', L'T' },
    { L'U', L'J' },
    { L'L', L'G' },
    { L'P', L'D' },
    { L'Z', L'T' },
    { L'L', L'U' },
    { L'K', L'Z' },
    { L'V', L'Q' },
    { L'K', L'G' },
    { L'E', L'Z' },
    { L'Z', L'Q' },
    { L'S', L'J' },
    { L'U', L'G' },
    { L'M', L'I' },
    { L'K', L'W' },
    { L'V', L'Y' },
    { L'Q', L'B' },
    { L'D', L'Y' },
    { L'G', L'I' },
    { L'S', L'A' },
    { L'S', L'X' },
    { L'N', L'O' },
    { L'X', L'M' },
    { L'Z', L'V' },
    { L'Z', L'W' },
    { L'L', L'C' },
    { L'G', L'Q' },
    { L'U', L'A' },
    { L'Z', L'G' },
    { L'Q', L'P' },
    { L'Z', L'C' },
    { L'K', L'U' },
    { L'L', L'Q' },
    { L'U', L'X' },
    { L'N', L'A' },
    { L'S', L'N' },
    { L'L', L'Z' },
    { L'D', L'F' },
    { L'A', L'D' },
    { L'K', L'J' },
    { L'Q', L'W' },
    { L'J', L'T' },
    { L'W', L'T' },
    { L'K', L'E' },
    { L'U', L'P' },
    { L'Z', L'O' },
    { L'B', L'D' },
    { L'J', L'R' },
    { L'A', L'O' },
    { L'E', L'N' },
    { L'G', L'D' },
    { L'Q', L'M' },
    { L'W', L'F' },
    { L'L', L'T' },
    { L'E', L'U' },
    { L'L', L'X' },
    { L'G', L'M' },
    { L'S', L'Z' },
    { L'Y', L'F' },
    { L'Z', L'N' },
    { L'U', L'T' },
    { L'O', L'D' },
    { L'X', L'H' },
    { L'E', L'V' },
    { L'T', L'M' },
    { L'O', L'Y' },
    { L'E', L'P' },
    { L'E', L'C' },
    { L'L', L'P' },
    { L'A', L'M' },
    { L'T', L'F' },
    { L'C', L'I' },
    { L'Z', L'X' },
    { L'U', L'Y' },
    { L'E', L'B' },
} };
